### ISSUE TITLE
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' 

### ISSUE THREAD

**Issue by vlyalcin** [Neurotech-HQ/heyoo#106]
Hi;

First of all, thank you for sharing this great work with everyone.

I am running the project on Ubuntu 24.04 LTS with Python 3.12, but I am encountering the following error.

```
(venv) user@server:~/project$ python hook.py
Traceback (most recent call last):
  File "/path/to/project/hook.py", line 5, in <module>
    from flask import Flask, request, make_response
  File "/path/to/project/venv/lib/python3.12/site-packages/flask/__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "/path/to/project/venv/lib/python3.12/site-packages/flask/app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/path/to/project/venv/lib/python3.12/site-packages/werkzeug/urls.py). Did you mean: 'unquote'?
```

Has anyone encountered this error before? How can I resolve it?

Thanks.

**Comment by vlyalcin** [comment]
According the information share in reference, I fixed the issue by specifying the lower version of the Werkzeug library in the requirements.txt file.

> Solution: Just set a fix version for Werkzeug such as Werkzeug==2.2.2 in your requirements.txt and it should work.

Reference: https://stackoverflow.com/a/77214086/1176555
